import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="flex justify-center items-center h-screen w-screen">
      <Head>
        <title>mrizkiaiman - v1 (Next 13)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className='text-3xl font-bold'>M. Rizki Aiman - NextJS 13 Boilerplate</p>
    </div>
  )
}
